### ISSUE TITLE
`numpyro` and `jax` version incompatibilities

### ISSUE THREAD

**Issue by joverlee521** [blab/evofr#31]
## Context
Latest run of forecasts-ncov models failed with 
```
[batch] [2024-02-08T21:42:57-08:00] Traceback (most recent call last):
[batch] [2024-02-08T21:42:57-08:00]   File "/nextstrain/build/./scripts/run-mlr-model.py", line 10, in <module>
[batch] [2024-02-08T21:42:57-08:00]     import evofr as ef
[batch] [2024-02-08T21:42:57-08:00]   File "/usr/local/lib/python3.10/site-packages/evofr/__init__.py", line 6, in <module>
[batch] [2024-02-08T21:42:57-08:00]     from .models import ModelSpec
[batch] [2024-02-08T21:42:57-08:00]   File "/usr/local/lib/python3.10/site-packages/evofr/models/__init__.py", line 2, in <module>
[batch] [2024-02-08T21:42:57-08:00]     from .multinomial_logistic_regression import MultinomialLogisticRegression
[batch] [2024-02-08T21:42:57-08:00]   File "/usr/local/lib/python3.10/site-packages/evofr/models/multinomial_logistic_regression.py", line 8, in <module>
[batch] [2024-02-08T21:42:57-08:00]     import numpyro
[batch] [2024-02-08T21:42:57-08:00]   File "/usr/local/lib/python3.10/site-packages/numpyro/__init__.py", line 6, in <module>
[batch] [2024-02-08T21:42:57-08:00]     from numpyro import compat, diagnostics, distributions, handlers, infer, ops, optim
[batch] [2024-02-08T21:42:57-08:00]   File "/usr/local/lib/python3.10/site-packages/numpyro/infer/__init__.py", line 5, in <module>
[batch] [2024-02-08T21:42:57-08:00]     from numpyro.infer.elbo import (
[batch] [2024-02-08T21:42:57-08:00]   File "/usr/local/lib/python3.10/site-packages/numpyro/infer/elbo.py", line 24, in <module>
[batch] [2024-02-08T21:42:57-08:00]     from numpyro.ops.provenance import eval_provenance
[batch] [2024-02-08T21:42:57-08:00]   File "/usr/local/lib/python3.10/site-packages/numpyro/ops/provenance.py", line 10, in <module>
[batch] [2024-02-08T21:42:57-08:00]     import jax.linear_util as lu
[batch] [2024-02-08T21:42:57-08:00] ModuleNotFoundError: No module named 'jax.linear_util'
```

A fresh install via `pip install evofr` installs `jax-0.4.24` and `numpyro-0.12.1` which are incompatible:

- `jax.linear_util` was moved to `jax.extend.linear_util` in [v0.4.16](https://github.com/google/jax/blob/main/CHANGELOG.md#jax-0416-sept-18-2023) and `jax.linear_util` was officially removed in [v0.4.24](https://github.com/google/jax/blob/main/CHANGELOG.md#jax-0424-feb-6-2024)
- `numpyro` only starts using the [new module in v0.13.1](https://github.com/pyro-ppl/numpyro/commit/115c4d3385b30a47c26ca88c4345605796d207c1#diff-4c4536389bff4797d7e4dbbf5af00a18367e70b23354d0e97dc6829ac1373546). 

## Possible solutions

1. pin `jax` to v0.4.23, before `jax.linear_util` was completely removed. 
2. bump minimum versions for both - `numpyro` to v0.13.2 and `jax` to v0.4.14 
    (I'm not familiar with the usage of `numpyro` in evofr so please refer to [releases](https://github.com/pyro-ppl/numpyro/releases) to check changes)

**Comment by marlinfiggins** [comment]
Hi Jover,

I went with the second solution here and bumped both jax and numpyro minimum versions. Numpyro is the framework that evofr uses for most of models we implement!

https://github.com/blab/evofr/commit/19b5b81ea753bc7d233028d9881d717d6cf06088

**Comment by joverlee521** [comment]
Thanks for the quick fix!
